"""
API Routes Package
==================
This package will contain Flask Blueprints for each API entity:
- students.py  → /api/students/...
- courses.py   → /api/courses/...
- semesters.py → /api/semesters/...
- enrollments.py → /api/enrollments/...

Each blueprint handles CRUD operations for one entity.
Blueprints will be registered in the app factory (app/__init__.py)
during Phase 3.
"""
